import type { DetectedItem, Meal, Recipe } from "./types";

export const meals: Meal[] = [
  {
    id: "breakfast",
    type: "Breakfast",
    name: "Eggs, sourdough & banana",
    description: "2 eggs · whole grain toast · 1 banana",
    time: "8:15 AM",
    art: "meal-art--breakfast",
    image: "/images/breakfast.jpg",
    calories: 420,
    protein: 22,
    carbs: 48,
    fat: 16,
    fiber: 7,
    confidence: 0.98,
    portion: "1 plate",
    tags: ["Protein", "Whole grain"],
  },
  {
    id: "lunch",
    type: "Lunch",
    name: "Phở bò",
    description: "Rice noodles · beef · herbs · bean sprouts",
    time: "12:40 PM",
    art: "meal-art--pho",
    image: "/images/pho-bo.jpg",
    calories: 560,
    protein: 28,
    carbs: 52,
    fat: 14,
    fiber: 5,
    confidence: 0.87,
    portion: "1 medium bowl",
    tags: ["Vietnamese", "High protein"],
  },
  {
    id: "snack",
    type: "Snack",
    name: "Greek yogurt & berries",
    description: "Plain yogurt · blueberries · pumpkin seeds",
    time: "3:30 PM",
    art: "meal-art--yogurt",
    image: "/images/yogurt-berries.jpg",
    calories: 210,
    protein: 17,
    carbs: 22,
    fat: 7,
    fiber: 4,
    confidence: 0.94,
    portion: "1 bowl",
    tags: ["Calcium", "Fiber"],
  },
];

export const detectedItems: DetectedItem[] = [
  { id: "beef", name: "Beef slices", detail: "Lean beef · cooked", portion: "80 g", confidence: 0.92 },
  { id: "noodles", name: "Rice noodles", detail: "Flat rice noodles", portion: "170 g", confidence: 0.89 },
  { id: "herbs", name: "Herbs & sprouts", detail: "Basil · cilantro · bean sprouts", portion: "45 g", confidence: 0.84 },
  { id: "broth", name: "Broth", detail: "Beef broth · seasoning estimate", portion: "350 ml", confidence: 0.71 },
];

export const recipes: Recipe[] = [
  {
    id: "lemongrass-chicken",
    title: "Lemongrass chicken bowl",
    description: "Bright herbs, brown rice, and a simple protein-forward bowl.",
    art: "recipe-art--chicken",
    image: "/images/chicken-bowl.jpg",
    time: "25 min",
    tag: "High protein",
    protein: "34 g",
    fiber: "8 g",
  },
  {
    id: "rainbow-rolls",
    title: "Rainbow gỏi cuốn",
    description: "Fresh vegetables, tofu, and herbs with a peanut-lime dip.",
    art: "recipe-art--rolls",
    image: "/images/spring-rolls.jpg",
    time: "20 min",
    tag: "Vegetarian",
    protein: "18 g",
    fiber: "9 g",
  },
  {
    id: "oats-yogurt",
    title: "Mango overnight oats",
    description: "A make-ahead breakfast with oats, yogurt, and seasonal fruit.",
    art: "recipe-art--oats",
    image: "/images/yogurt-berries.jpg",
    time: "10 min",
    tag: "Quick meal",
    protein: "16 g",
    fiber: "10 g",
  },
];

export const searchFoods = [
  { name: "Phở bò", category: "Vietnamese · noodle soup", calories: 560, protein: 28, fiber: 5, source: "Curated Vietnamese food table" },
  { name: "Cơm tấm", category: "Vietnamese · rice plate", calories: 640, protein: 31, fiber: 4, source: "Curated Vietnamese food table" },
  { name: "Grilled chicken breast", category: "Protein · cooked", calories: 284, protein: 53, fiber: 0, source: "USDA FoodData Central" },
  { name: "Gỏi cuốn", category: "Vietnamese · fresh roll", calories: 180, protein: 8, fiber: 3, source: "Curated Vietnamese food table" },
];
