import type { DetectedItem, FoodDatabaseEntry, Meal, Recipe, UserProfile } from "./types";
import { DEFAULT_GOALS } from "./services/nutritionEngine";

export const initialUserProfile: UserProfile = {
  name: "Thanh Nguyen",
  email: "thanh.nguyen@example.com",
  avatarText: "T",
  accountType: "Personal Pro",
  memberSince: "August 2026",
  dietaryPreference: "Balanced with Vietnamese focus",
  allergies: ["No known allergies"],
  nutritionInterests: ["High protein variety", "Fiber optimization", "Mindful eating"],
  goals: DEFAULT_GOALS,
};

export const initialMeals: Meal[] = [
  {
    id: "breakfast",
    type: "Breakfast",
    name: "Eggs, Sourdough & Banana",
    description: "2 pasture-raised eggs · toasted sourdough · fresh banana slices",
    time: "8:15 AM",
    date: "Today, Aug 22",
    art: "meal-art--breakfast",
    image: "/images/breakfast.jpg",
    calories: 420,
    protein: 22,
    carbs: 48,
    fat: 16,
    fiber: 7,
    sodium: 380,
    confidence: 0.98,
    portion: "1 medium plate",
    tags: ["Whole grain", "High protein"],
    source: "USDA FoodData Central",
    items: [
      { id: "egg", name: "Whole Eggs (Poached)", detail: "2 large eggs", portion: "100 g", amount: 100, unit: "g", calories: 140, protein: 12, carbs: 1, fat: 10, fiber: 0, confidence: 0.99, source: "USDA FoodData Central" },
      { id: "bread", name: "Sourdough Bread", detail: "Toasted slice", portion: "60 g", amount: 60, unit: "g", calories: 160, protein: 6, carbs: 32, fat: 1, fiber: 2, confidence: 0.97, source: "USDA FoodData Central" },
      { id: "banana", name: "Fresh Banana", detail: "1 medium", portion: "118 g", amount: 118, unit: "g", calories: 120, protein: 4, carbs: 15, fat: 5, fiber: 5, confidence: 0.98, source: "USDA FoodData Central" },
    ],
  },
  {
    id: "lunch",
    type: "Lunch",
    name: "Phở Bò (Beef Noodle Soup)",
    description: "Flat rice noodles · tender lean beef · fresh herbs · simmered broth",
    time: "12:40 PM",
    date: "Today, Aug 22",
    art: "meal-art--pho",
    image: "/images/pho-bo.jpg",
    calories: 560,
    protein: 28,
    carbs: 52,
    fat: 14,
    fiber: 5,
    sodium: 1100,
    confidence: 0.87,
    portion: "1 medium bowl",
    tags: ["Vietnamese", "High protein"],
    source: "Curated Vietnamese Food Table",
    items: [
      { id: "beef", name: "Lean Beef Slices", detail: "Cooked tenderloin", portion: "80 g", amount: 80, unit: "g", calories: 175, protein: 21, carbs: 0, fat: 9, fiber: 0, confidence: 0.92, source: "Curated Vietnamese Food Table" },
      { id: "noodles", name: "Fresh Flat Rice Noodles", detail: "Bánh phở tươi", portion: "170 g", amount: 170, unit: "g", calories: 230, protein: 4, carbs: 48, fat: 1, fiber: 2, confidence: 0.89, source: "Curated Vietnamese Food Table" },
      { id: "herbs", name: "Fresh Herbs & Bean Sprouts", detail: "Thai basil, cilantro, giá sống", portion: "60 g", amount: 60, unit: "g", calories: 25, protein: 2, carbs: 3, fat: 0, fiber: 3, confidence: 0.86, source: "Curated Vietnamese Food Table" },
      { id: "broth", name: "Traditional Beef Bone Broth", detail: "Herbal infused broth", portion: "350 ml", amount: 350, unit: "ml", calories: 130, protein: 1, carbs: 1, fat: 4, fiber: 0, confidence: 0.81, source: "Curated Vietnamese Food Table" },
    ],
  },
  {
    id: "snack",
    type: "Snack",
    name: "Greek Yogurt & Blueberries",
    description: "Non-fat greek yogurt · organic blueberries · pumpkin seeds",
    time: "3:30 PM",
    date: "Today, Aug 22",
    art: "meal-art--yogurt",
    image: "/images/yogurt-berries.jpg",
    calories: 210,
    protein: 17,
    carbs: 22,
    fat: 7,
    fiber: 4,
    sodium: 65,
    confidence: 0.94,
    portion: "1 small bowl",
    tags: ["Probiotics", "Antioxidants"],
    source: "USDA FoodData Central",
    items: [
      { id: "yogurt", name: "Greek Yogurt (Plain)", detail: "0% milkfat", portion: "150 g", amount: 150, unit: "g", calories: 100, protein: 15, carbs: 6, fat: 0, fiber: 0, confidence: 0.98, source: "USDA FoodData Central" },
      { id: "blueberries", name: "Fresh Blueberries", detail: "Wild organic", portion: "75 g", amount: 75, unit: "g", calories: 45, protein: 1, carbs: 11, fat: 0, fiber: 2, confidence: 0.95, source: "USDA FoodData Central" },
      { id: "seeds", name: "Pumpkin Seeds", detail: "Raw shelled pepitas", portion: "15 g", amount: 15, unit: "g", calories: 65, protein: 1, carbs: 5, fat: 7, fiber: 2, confidence: 0.89, source: "USDA FoodData Central" },
    ],
  },
];

export const detectedItems: DetectedItem[] = [
  {
    id: "beef",
    name: "Lean Beef Slices",
    detail: "Cooked lean beef · tenderloin",
    portion: "80 g",
    amount: 80,
    unit: "g",
    baseCalories: 218,
    baseProtein: 26,
    baseCarbs: 0,
    baseFat: 11,
    baseFiber: 0,
    confidence: 0.92,
    source: "Curated Vietnamese Food Table",
  },
  {
    id: "noodles",
    name: "Rice Noodles (Bánh Phở)",
    detail: "Fresh flat rice noodles",
    portion: "170 g",
    amount: 170,
    unit: "g",
    baseCalories: 135,
    baseProtein: 2.5,
    baseCarbs: 28,
    baseFat: 0.5,
    baseFiber: 1.2,
    confidence: 0.89,
    source: "Curated Vietnamese Food Table",
  },
  {
    id: "herbs",
    name: "Herbs & Sprouts",
    detail: "Thai basil, cilantro, bean sprouts",
    portion: "50 g",
    amount: 50,
    unit: "g",
    baseCalories: 35,
    baseProtein: 3,
    baseCarbs: 5,
    baseFat: 0.5,
    baseFiber: 4.5,
    confidence: 0.85,
    source: "Curated Vietnamese Food Table",
  },
  {
    id: "broth",
    name: "Beef Bone Broth",
    detail: "Star anise & cinnamon infused broth",
    portion: "350 ml",
    amount: 350,
    unit: "ml",
    baseCalories: 38,
    baseProtein: 0.5,
    baseCarbs: 0.5,
    baseFat: 1.2,
    baseFiber: 0,
    confidence: 0.76,
    source: "Curated Vietnamese Food Table",
  },
];

export const recipes: Recipe[] = [
  {
    id: "lemongrass-chicken",
    title: "Lemongrass Chicken Brown Rice Bowl",
    description: "A fragrant citrus-marinated grilled chicken breast served over warm brown rice, pickled daikon, and crisp cucumbers.",
    art: "recipe-art--chicken",
    image: "/images/chicken-bowl.jpg",
    time: "25 min",
    prepTime: "10 min",
    cookTime: "15 min",
    servings: 2,
    difficulty: "Easy",
    tag: "High protein",
    cuisine: "Vietnamese Modern",
    calories: 480,
    protein: "38 g",
    carbs: "54 g",
    fat: "12 g",
    fiber: "8 g",
    ingredients: [
      { name: "Boneless chicken breast", amount: "300 g", calories: 360 },
      { name: "Minced fresh lemongrass", amount: "2 tbsp" },
      { name: "Garlic & shallot paste", amount: "1 tbsp" },
      { name: "Cooked brown jasmine rice", amount: "1.5 cups", calories: 320 },
      { name: "Pickled daikon & carrots (Đồ chua)", amount: "80 g", calories: 45 },
      { name: "Fresh cucumber & cilantro", amount: "1 cup" },
    ],
    instructions: [
      "Marinate sliced chicken with minced lemongrass, garlic, a splash of light soy sauce, and 1 tsp sesame oil for 10 minutes.",
      "Heat a cast-iron skillet over medium-high heat. Sear the chicken for 5-6 minutes on each side until lightly charred and fully cooked.",
      "Assemble bowls: scoop cooked brown rice into each bowl, top with sliced lemongrass chicken, pickled veggies, and fresh herbs.",
      "Serve with a light lime-garlic dressing on the side.",
    ],
    nutritionSummary: {
      calories: 480,
      protein: 38,
      carbs: 54,
      fat: 12,
      fiber: 8,
      sodium: 480,
      sugar: 4,
    },
  },
  {
    id: "rainbow-rolls",
    title: "Rainbow Gỏi Cuốn (Fresh Summer Rolls)",
    description: "Translucent rice paper wrapped around crisp red cabbage, firm organic tofu, avocado slices, and aromatic mint leaves.",
    art: "recipe-art--rolls",
    image: "/images/spring-rolls.jpg",
    time: "20 min",
    prepTime: "20 min",
    cookTime: "0 min",
    servings: 2,
    difficulty: "Easy",
    tag: "Vegetarian",
    cuisine: "Vietnamese",
    calories: 320,
    protein: "18 g",
    carbs: "38 g",
    fat: "11 g",
    fiber: "9 g",
    ingredients: [
      { name: "Vietnamese rice paper (Bánh tráng)", amount: "6 sheets", calories: 180 },
      { name: "Pan-seared firm organic tofu", amount: "150 g", calories: 160 },
      { name: "Shredded purple cabbage & carrot", amount: "1 cup", calories: 40 },
      { name: "Fresh mint, Thai basil & cilantro", amount: "1 bunch" },
      { name: "Thinly sliced avocado", amount: "0.5 fruit", calories: 120 },
      { name: "Peanut-lime dipping sauce", amount: "3 tbsp", calories: 140 },
    ],
    instructions: [
      "Dip one rice paper sheet into lukewarm water for 3 seconds, then lay flat on a clean board.",
      "Layer fresh herbs, tofu strips, sliced avocado, and shredded rainbow vegetables across the bottom third of the paper.",
      "Fold the sides inward tightly, then roll firmly upwards from the bottom until sealed.",
      "Slice rolls in half diagonally and serve immediately with peanut-lime dipping sauce.",
    ],
    nutritionSummary: {
      calories: 320,
      protein: 18,
      carbs: 38,
      fat: 11,
      fiber: 9,
      sodium: 320,
      sugar: 5,
    },
  },
  {
    id: "oats-yogurt",
    title: "Mango Chia Overnight Oats",
    description: "Rolled oats steeped in creamy oat milk, layered with probiotic Greek yogurt, chia seeds, and sweet Alphonso mango cubes.",
    art: "recipe-art--oats",
    image: "/images/yogurt-berries.jpg",
    time: "10 min",
    prepTime: "10 min",
    cookTime: "0 min",
    servings: 1,
    difficulty: "Easy",
    tag: "Quick meal",
    cuisine: "Modern Breakfast",
    calories: 360,
    protein: "19 g",
    carbs: "52 g",
    fat: "8 g",
    fiber: "11 g",
    ingredients: [
      { name: "Old-fashioned rolled oats", amount: "50 g", calories: 190 },
      { name: "Unsweetened almond/oat milk", amount: "120 ml", calories: 45 },
      { name: "Black chia seeds", amount: "1 tbsp", calories: 60 },
      { name: "Plain non-fat Greek yogurt", amount: "100 g", calories: 60 },
      { name: "Diced fresh sweet mango", amount: "80 g", calories: 50 },
    ],
    instructions: [
      "In a glass jar, stir together rolled oats, chia seeds, and plant milk until fully combined.",
      "Cover and chill in the refrigerator overnight (or for at least 4 hours).",
      "In the morning, top with a layer of cold Greek yogurt and diced ripe mango.",
      "Sprinkle a pinch of toasted coconut or crushed walnuts if desired.",
    ],
    nutritionSummary: {
      calories: 360,
      protein: 19,
      carbs: 52,
      fat: 8,
      fiber: 11,
      sodium: 70,
      sugar: 14,
    },
  },
];

export const searchFoods: FoodDatabaseEntry[] = [
  { id: "db_pho_bo", name: "Phở bò (Beef noodle soup)", category: "Vietnamese noodle soup", serving: "1 medium bowl (500g)", defaultAmount: 100, unit: "g", calories: 112, protein: 5.6, carbs: 10.4, fat: 2.8, fiber: 1.0, source: "Curated Vietnamese Food Table" },
  { id: "db_com_tam", name: "Cơm tấm sườn nướng (Broken rice with pork)", category: "Vietnamese rice plate", serving: "1 plate (450g)", defaultAmount: 100, unit: "g", calories: 142, protein: 6.9, carbs: 18.2, fat: 4.8, fiber: 0.9, source: "Curated Vietnamese Food Table" },
  { id: "db_chicken_breast", name: "Grilled Chicken Breast (Skinless)", category: "Lean Poultry", serving: "1 fillet (150g)", defaultAmount: 100, unit: "g", calories: 165, protein: 31.0, carbs: 0.0, fat: 3.6, fiber: 0.0, source: "USDA FoodData Central" },
  { id: "db_goi_cuon", name: "Gỏi cuốn tôm thịt (Fresh shrimp roll)", category: "Vietnamese appetizer", serving: "2 rolls (140g)", defaultAmount: 100, unit: "g", calories: 128, protein: 5.7, carbs: 17.1, fat: 2.1, fiber: 2.1, source: "Curated Vietnamese Food Table" },
  { id: "db_salmon", name: "Wild Alaskan Salmon (Baked)", category: "Seafood", serving: "1 fillet (140g)", defaultAmount: 100, unit: "g", calories: 182, protein: 25.4, carbs: 0.0, fat: 8.1, fiber: 0.0, source: "USDA FoodData Central" },
  { id: "db_brown_rice", name: "Cooked Brown Jasmine Rice", category: "Whole Grains", serving: "1 cup (195g)", defaultAmount: 100, unit: "g", calories: 111, protein: 2.6, carbs: 23.0, fat: 0.9, fiber: 1.8, source: "USDA FoodData Central" },
  { id: "db_avocado", name: "Fresh Hass Avocado", category: "Healthy Fats & Fruit", serving: "0.5 fruit (100g)", defaultAmount: 100, unit: "g", calories: 160, protein: 2.0, carbs: 8.5, fat: 14.7, fiber: 6.7, source: "USDA FoodData Central" },
  { id: "db_tofu", name: "Organic Firm Tofu", category: "Plant Protein", serving: "100 g", defaultAmount: 100, unit: "g", calories: 83, protein: 10.0, carbs: 2.0, fat: 5.0, fiber: 1.2, source: "USDA FoodData Central" },
  { id: "db_dragonfruit", name: "Fresh Dragon Fruit (Thanh Long)", category: "Fresh Tropical Fruit", serving: "1 cup diced (150g)", defaultAmount: 100, unit: "g", calories: 60, protein: 1.2, carbs: 13.0, fat: 0.5, fiber: 2.9, source: "Curated Vietnamese Food Table" },
];

export const weeklyNutrientTrends = [
  { day: "Mon", fullDay: "Monday", date: "Aug 17", protein: 78, fiber: 22, calories: 1940, plantCount: 4, waterL: 2.2 },
  { day: "Tue", fullDay: "Tuesday", date: "Aug 18", protein: 84, fiber: 29, calories: 2050, plantCount: 6, waterL: 2.6 },
  { day: "Wed", fullDay: "Wednesday", date: "Aug 19", protein: 72, fiber: 26, calories: 1880, plantCount: 5, waterL: 2.4 },
  { day: "Thu", fullDay: "Thursday", date: "Aug 20", protein: 92, fiber: 31, calories: 2120, plantCount: 7, waterL: 2.5 },
  { day: "Fri", fullDay: "Friday", date: "Aug 21", protein: 68, fiber: 24, calories: 1820, plantCount: 4, waterL: 2.0 },
  { day: "Sat", fullDay: "Saturday (Today)", date: "Aug 22", protein: 67, fiber: 16, calories: 1190, plantCount: 4, waterL: 1.4 },
  { day: "Sun", fullDay: "Sunday (Forecast)", date: "Aug 23", protein: 80, fiber: 28, calories: 1950, plantCount: 5, waterL: 2.4 },
];
